### ISSUE TITLE
What sort of contributions, if any, are you interested in?

### ISSUE THREAD

**Issue by JohnDMcMaster** [fail0verflow/rl78-debug#1]
Thanks for posting this!

I have some local modifications. Are you interested in PRs for any of the following:
-General fixes (ex: struct format bug)
-Linux usability improvements
-README with some quick start instructions
-pep8 reformat

In the meantime I'll develop as I see fit and push to my fork (https://github.com/JohnDMcMaster/rl78-debug)

**Comment by shuffle2** [comment]
tbh the code hasn't been touched/used for ages, but if you'd like to submit your changes as PR they sound good.

**Comment by JohnDMcMaster** [comment]
Cool! Will do once I test things a bit more

**Comment by JohnDMcMaster** [comment]
BTW this project ended up making significant progress, although a bit delayed. I ported the code to rp2040, expanded the functionality, and made a new trojan. i also have related dev board(s) and documentation. I'll try to do a writeup at some point and/or push more things out

**Comment by udif** [comment]
What happened to the rprl78-src repo?

**Comment by JohnDMcMaster** [comment]
I made it public and people started opening tickets saying they wanted help pirating things. Was more trouble than it was worth so I removed it

**Comment by udif** [comment]
Which gaming console is using an RL78 ? 😃 

Pity. Were there any huge functional differences between it and the existing version, other than the different platform?

EDIT: A quick google for "RL78 console" eventually brought up everything I needed to understand you...
